
-- Add comprehensive state insurance regulations for NJ, PA, TX, and FL

-- NJ Additional Regulations
INSERT INTO state_insurance_regulations (state_code, state_name, regulation_type, regulation_title, regulation_citation, deadline_days, description, consequence_description) VALUES
('NJ', 'New Jersey', 'unfair_claims', 'Misrepresentation of Policy Provisions', 'N.J.A.C. 11:2-17.8(a)', NULL, 'Insurers shall not misrepresent pertinent facts or policy provisions relating to coverages at issue. Making false statements about coverage, exclusions, or policy conditions to deny or reduce a claim is a violation.', 'Regulatory enforcement action, fines, and potential bad faith liability'),
('NJ', 'New Jersey', 'unfair_claims', 'Failure to Affirm or Deny Coverage', 'N.J.A.C. 11:2-17.6(d)', 30, 'Insurers must affirm or deny coverage of claims within a reasonable time after proof of loss. Failing to provide a clear coverage determination forces the policyholder into uncertainty.', 'Regulatory penalties and potential bad faith exposure'),
('NJ', 'New Jersey', 'unfair_claims', 'Failure to Provide Reasonable Explanation for Denial', 'N.J.A.C. 11:2-17.8(c)', NULL, 'When denying a claim, insurers must provide a reasonable explanation based on the policy terms. Vague, unsupported, or pretextual denial reasons violate this provision.', 'Denial may be overturned; regulatory penalties'),
('NJ', 'New Jersey', 'unfair_claims', 'Compelling Litigation by Offering Substantially Less', 'N.J.A.C. 11:2-17.8(e)', NULL, 'Insurers shall not compel insureds to institute litigation to recover amounts due by offering substantially less than the amounts ultimately recovered in actions brought by such insureds.', 'Bad faith damages, regulatory fines'),
('NJ', 'New Jersey', 'unfair_claims', 'Failing to Promptly Settle When Liability Is Clear', 'N.J.A.C. 11:2-17.8(d)', NULL, 'Insurers must attempt in good faith to promptly settle claims in which liability has become reasonably clear. Delaying payment to pressure policyholders is prohibited.', 'Regulatory action and bad faith penalties'),
('NJ', 'New Jersey', 'bad_faith', 'Unfair Investigation Practices', 'N.J.A.C. 11:2-17.9', NULL, 'Insurers must conduct reasonable investigations based on all available information. Making coverage determinations based on incomplete investigations, ignoring evidence, or relying on biased engineering reports without independent verification violates this regulation.', 'Bad faith liability, regulatory enforcement'),
('NJ', 'New Jersey', 'unfair_claims', 'Not Attempting Good Faith Settlement', 'N.J.A.C. 11:2-17.8(f)', NULL, 'Insurers may not deny a claim based on a specific policy exclusion or condition without demonstrating that the exclusion or condition applies to the specific facts of the loss.', 'Regulatory penalties and potential litigation exposure'),
('NJ', 'New Jersey', 'unfair_claims', 'Requiring Unreasonable Documentation', 'N.J.A.C. 11:2-17.8(b)', NULL, 'Insurers shall not require submission of unreasonable or duplicative documentation as a condition of claim payment when such documentation is not materially relevant to the claim.', 'Regulatory penalties'),

-- PA Additional Regulations  
('PA', 'Pennsylvania', 'unfair_claims', 'Misrepresentation of Policy Provisions', '40 P.S. § 1171.5(a)(1)', NULL, 'Misrepresenting pertinent facts or insurance policy provisions relating to coverages at issue constitutes an unfair claims settlement practice under Pennsylvania law.', 'Administrative penalties, cease and desist orders, license revocation'),
('PA', 'Pennsylvania', 'unfair_claims', 'Failing to Acknowledge Communications', '40 P.S. § 1171.5(a)(2)', 10, 'Failing to acknowledge and act reasonably promptly upon communications with respect to claims arising under insurance policies. All communications must be acknowledged within 10 business days.', 'Regulatory penalties per violation'),
('PA', 'Pennsylvania', 'unfair_claims', 'Failing to Adopt Reasonable Standards for Investigation', '40 P.S. § 1171.5(a)(3)', NULL, 'Failing to adopt and implement reasonable standards for the prompt investigation of claims arising under insurance policies. Carriers cannot rely on biased or predetermined investigation outcomes.', 'Per-violation fines, license action'),
('PA', 'Pennsylvania', 'unfair_claims', 'Refusing to Pay Without Reasonable Investigation', '40 P.S. § 1171.5(a)(4)', NULL, 'Refusing to pay claims without conducting a reasonable investigation based upon all available information. Making accusations of man-made damage, wear and tear, or pre-existing conditions without documented proof constitutes a violation.', 'Bad faith liability under 42 Pa.C.S. § 8371'),
('PA', 'Pennsylvania', 'unfair_claims', 'Not Attempting Good Faith Settlement', '40 P.S. § 1171.5(a)(6)', NULL, 'Not attempting in good faith to effectuate prompt, fair, and equitable settlements of claims in which liability has become reasonably clear.', 'Bad faith damages including punitive damages'),
('PA', 'Pennsylvania', 'unfair_claims', 'Compelling Insureds to Institute Litigation', '40 P.S. § 1171.5(a)(7)', NULL, 'Compelling insureds to institute litigation to recover amounts due under an insurance policy by offering substantially less than the amounts ultimately recovered in actions brought by such insureds.', 'Bad faith treble damages potential'),
('PA', 'Pennsylvania', 'bad_faith', 'Unreasonable Denial or Delay of Benefits', '42 Pa.C.S. § 8371', NULL, 'A court may award interest, punitive damages, court costs, and attorney fees when an insurer acts in bad faith toward an insured. Bad faith includes lack of a reasonable basis for denying benefits and knowledge or reckless disregard of the lack of a reasonable basis.', 'Interest on claim amount, punitive damages, attorney fees, court costs'),
('PA', 'Pennsylvania', 'unfair_claims', 'Failing to Provide Reasonable Explanation', '40 P.S. § 1171.5(a)(14)', NULL, 'Failing to promptly provide a reasonable explanation of the basis in the insurance policy in relation to the facts or applicable law for denial of a claim or for the offer of a compromise settlement.', 'Per-violation regulatory fines'),

-- TX Regulations
('TX', 'Texas', 'insurer_response', 'Acknowledgment of Claim', 'Tex. Ins. Code § 542.055', 15, 'An insurer must acknowledge receipt of a claim not later than the 15th day after the date the claim is received, and request all items, statements, and forms the insurer reasonably believes will be required.', 'Statutory penalties and interest on delayed payments'),
('TX', 'Texas', 'insurer_response', 'Claim Decision Deadline', 'Tex. Ins. Code § 542.056', 15, 'An insurer shall notify the claimant in writing of the acceptance or rejection of the claim not later than the 15th business day after the insurer receives all items, statements, and forms required.', '18% annual interest penalty on overdue payments'),
('TX', 'Texas', 'insurer_response', 'Payment Deadline After Acceptance', 'Tex. Ins. Code § 542.057', 5, 'If an insurer notifies a claimant that the claim is accepted, the insurer must pay the claim not later than the 5th business day after notice of acceptance.', '18% annual interest plus attorney fees'),
('TX', 'Texas', 'unfair_claims', 'Unfair Settlement Practices', 'Tex. Ins. Code § 541.060', NULL, 'Engaging in unfair settlement practices includes: misrepresenting to a claimant a material fact or policy provision, failing to attempt in good faith to effectuate a prompt and equitable settlement when liability is reasonably clear, and making an offer of settlement that is unreasonably low.', 'Actual damages, treble damages for knowing violations, attorney fees'),
('TX', 'Texas', 'unfair_claims', 'Misrepresentation of Policy Provisions', 'Tex. Ins. Code § 541.060(a)(1)', NULL, 'Misrepresenting to a claimant a material fact or policy provision relating to coverage at issue is a prohibited unfair settlement practice.', 'Treble damages for knowing violations'),
('TX', 'Texas', 'unfair_claims', 'Failure to Conduct Reasonable Investigation', 'Tex. Ins. Code § 541.060(a)(7)', NULL, 'Refusing to pay a claim without conducting a reasonable investigation with respect to the claim. Relying on biased reports or making unsupported accusations about the cause of damage violates this provision.', 'Actual and treble damages plus attorney fees'),
('TX', 'Texas', 'bad_faith', 'Bad Faith - Breach of Duty of Good Faith', 'Common Law / Tex. Ins. Code Ch. 541', NULL, 'Texas recognizes a common law duty of good faith and fair dealing. An insurer that denies or delays a claim without a reasonable basis, or that makes baseless accusations about the cause of loss, breaches this duty.', 'Compensatory damages, mental anguish damages, punitive damages'),
('TX', 'Texas', 'unfair_claims', 'Requiring Fraudulent Proof or Excessive Documentation', 'Tex. Ins. Code § 541.060(a)(3)', NULL, 'Failing to adopt and implement reasonable standards for prompt investigation and processing of claims. Requiring excessive, duplicative, or irrelevant documentation to delay claim resolution is prohibited.', 'Regulatory penalties and damages'),
('TX', 'Texas', 'insurer_response', 'Delay Notice Requirement', 'Tex. Ins. Code § 542.056(d)', 45, 'If the insurer cannot accept or reject the claim within the initial deadline, the insurer must notify the claimant of the reasons and expected resolution date, not to exceed 45 days.', '18% annual interest on amount owed'),

-- FL Regulations
('FL', 'Florida', 'insurer_response', 'Acknowledgment of Claim', 'Fla. Stat. § 627.70131(1)(a)', 14, 'Within 14 days after receiving a communication regarding a claim, the insurer must acknowledge the communication and provide necessary claim forms and instructions.', 'Regulatory penalties and enforcement action'),
('FL', 'Florida', 'insurer_response', 'Claim Investigation and Decision', 'Fla. Stat. § 627.70131(5)(a)', 90, 'The insurer must pay or deny a claim within 90 days after receiving notice of the claim. Failure to pay undisputed amounts within the statutory timeframe triggers penalties.', 'Interest penalties and regulatory enforcement'),
('FL', 'Florida', 'insurer_response', 'Payment After Determination', 'Fla. Stat. § 627.70131(5)(b)', 20, 'Within 20 days after the insurer determines full or partial coverage exists, the insurer must tender payment of the undisputed amount.', 'Statutory interest penalties'),
('FL', 'Florida', 'unfair_claims', 'Unfair Claim Settlement Practices', 'Fla. Stat. § 626.9541(1)(i)', NULL, 'Committing or performing with such frequency as to indicate a general business practice: attempting to settle claims on the basis of an application altered without notice, misrepresenting pertinent facts or policy provisions, failing to promptly settle claims when liability is clear.', 'Administrative fines up to $5,000 per violation, license suspension or revocation'),
('FL', 'Florida', 'unfair_claims', 'Not Attempting Good Faith Settlement', 'Fla. Stat. § 626.9541(1)(i)(3)(c)', NULL, 'Failing to promptly settle claims, when liability has become reasonably clear, under one portion of the insurance policy coverage in order to influence settlements under other portions of the insurance policy coverage.', 'Per-violation fines, license action'),
('FL', 'Florida', 'unfair_claims', 'Denying Claims Without Reasonable Investigation', 'Fla. Stat. § 626.9541(1)(i)(3)(d)', NULL, 'Refusing to pay claims without conducting a reasonable investigation based upon available information. Making unsupported accusations of pre-existing damage, man-made damage, or wear and tear without physical evidence violates this provision.', 'Administrative penalties and civil remedy'),
('FL', 'Florida', 'bad_faith', 'Civil Remedy for Bad Faith', 'Fla. Stat. § 624.155', NULL, 'Any person may bring a civil action against an insurer who does not attempt in good faith to settle claims when the obligation to settle is reasonably clear. This includes making determinations of non-coverage without a reasonable factual or legal basis.', 'Compensatory damages, attorney fees, court costs, consequential damages'),
('FL', 'Florida', 'unfair_claims', 'Misrepresentation of Policy Provisions', 'Fla. Stat. § 626.9541(1)(i)(3)(a)', NULL, 'Misrepresenting pertinent facts or insurance policy provisions relating to coverages at issue in the adjustment of a claim.', 'Administrative fines, license suspension'),
('FL', 'Florida', 'pol_deadline', 'Proof of Loss Deadline', 'Standard Policy Form', 60, 'Standard Florida homeowners policies require the insured to submit a signed, sworn proof of loss within 60 days after the insurer requests it.', 'Failure to submit may jeopardize claim recovery'),
('TX', 'Texas', 'pol_deadline', 'Proof of Loss Deadline', 'Standard Policy Form', 91, 'Standard Texas homeowners policies require the insured to submit a signed, sworn proof of loss within 91 days after the loss.', 'Failure to submit may jeopardize claim recovery')
ON CONFLICT DO NOTHING;
