// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { publishDarwinKbDebug } from "@/lib/darwinKbDebugBus";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

const originalInvoke = supabase.functions.invoke.bind(supabase.functions);

(supabase.functions as any).invoke = async (functionName: string, options?: any) => {
  const response = await originalInvoke(functionName, options);

  try {
    if (functionName === "darwin-ai-analysis") {
      const payload = response?.data && typeof response.data === "object" ? response.data : null;
      const requestBody = options?.body && typeof options.body === "object" ? options.body : {};
      const claimId = payload?.claimId || requestBody.claimId || requestBody.claim_id || "";
      const analysisType = payload?.analysisType || requestBody.analysisType || requestBody.analysis_type || "unknown";
      const sources = Array.isArray(payload?.sources) ? payload.sources : [];

      publishDarwinKbDebug({
        claimId: String(claimId),
        analysisType: String(analysisType),
        usedKb: Boolean(payload?.usedKb),
        retrieval: payload?.retrieval || null,
        sources,
        diagnosticHint: payload?.diagnosticHint || payload?.retrieval?.health?.diagnosticHint || null,
        error: payload?.error || null,
        timestamp: new Date().toISOString(),
      });
    }
  } catch (debugError) {
    console.error("Failed to publish Darwin KB debug event:", debugError);
  }

  return response;
};